
services:
 
  web-app:

    build: .


    image: my-compose-app:latest
    

    container_name: my-compose-container
    

    ports:
      - "3000:3000"

    volumes:
      - .:/usr/src/app                   

    command: sh -c "bun install && bun --watch run dev"